version: '3'

services:

  web:
    build: .
    environment:
      TZ: "Europe/Prague"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  localpy:
    build: .
    environment:
      TZ: "Europe/Prague"
    command: python main.py
    volumes:
      - .:/code
